### ISSUE TITLE
Need a help in running Xamarin.UI.Test for IOS app

### ISSUE THREAD

**Issue by abhi-debuginside** [UdaraAlwis/XAMVVM-Playground#1]
The app is not getting invoked when we try to run UI test against IOS app in MAC machine using visual studio. The error it showing is the **Timeout exception.**

_The Driver Agent is just open and close immediately and nothing is happening to my app._

**Comment by UdaraAlwis** [comment]
Hey there, sorry about the delay, I must have missed out on this thread. 
Regarding your my guess would be the UITest runner is unable to find the path to the IPA file, or the app package name, then again it depends on how you have configured your iOS Test initialisation. Checking against those would surely help.
Cheers!
